helm:
  parameters:
  - name: image.repository
    value: ghcr.io/dungbik/flipnote-user
    forcestring: true
  - name: image.tag
    value: main@sha256:5f613db0eea45b58d0ec108f50c45bba1dc4f2548d0877c1102b8028e8ec2824
    forcestring: true
