helm:
  parameters:
  - name: image.repository
    value: ghcr.io/dungbik/flipnote-user
    forcestring: true
  - name: image.tag
    value: main@sha256:2eb0cc86a257086bbcf28b10e4ef048741b07538a3c81f4d94ff700ea602ee5f
    forcestring: true
