helm:
  parameters:
  - name: image.repository
    value: ghcr.io/dungbik/flipnote-api-gateway
    forcestring: true
  - name: image.tag
    value: main@sha256:91fa539571e03ea85d33dbae55630fe5feea4f5cd3aa587ee742421b05b280a1
    forcestring: true
