helm:
  parameters:
  - name: image.repository
    value: ghcr.io/dungbik/flipnote-api-gateway
    forcestring: true
  - name: image.tag
    value: main@sha256:1617619a9f09199d251d2eb96611566488e798421d6e74d5183ccc6c1ae3139f
    forcestring: true
