helm:
  parameters:
  - name: image.repository
    value: ghcr.io/dungbik/flipnote-api-gateway
    forcestring: true
  - name: image.tag
    value: main@sha256:ada3472e560faaab4caf49f272fec2a3fac5b24160ff459d45d7be1ea89aec42
    forcestring: true
