helm:
  parameters:
  - name: image.repository
    value: ghcr.io/dungbik/flipnote-reaction
    forcestring: true
  - name: image.tag
    value: main@sha256:6acbf93a64cac6832aaffac436234b0a87332d84fdf83fd7b6ef98a90550f69e
    forcestring: true
