helm:
  parameters:
  - name: image.repository
    value: dungbik/flipnote-reaction
    forcestring: true
  - name: image.tag
    value: main@sha256:2c0ab7ac8633d17712e655d33c79bdd452117e45b1985b6e91b3d05179ca5da5
    forcestring: true
