helm:
  parameters:
  - name: image.repository
    value: ghcr.io/dungbik/flipnote-group
    forcestring: true
  - name: image.tag
    value: main@sha256:ec050716a43805cd4f718ecebb894cbe729b2acf685a1fa9d5de4cff21295d3c
    forcestring: true
