helm:
  parameters:
  - name: image.repository
    value: ghcr.io/dungbik/flipnote-group
    forcestring: true
  - name: image.tag
    value: main@sha256:fbd0ccf634f0a301da45978aac276b09cf4001ae9ee442856c29af90a80749af
    forcestring: true
