helm:
  parameters:
  - name: image.repository
    value: ghcr.io/dungbik/flipnote-notification
    forcestring: true
  - name: image.tag
    value: main@sha256:14a117808d31571adfcccc4336cbb845faca2bea40d8985634523c5ae9540224
    forcestring: true
