helm:
  parameters:
  - name: image.repository
    value: ghcr.io/dungbik/flipnote-notification
    forcestring: true
  - name: image.tag
    value: main@sha256:ee5691ff2ccfd1bf3f05c8c7f08f2e19b3e1039a1800659d465d290a5dae7d26
    forcestring: true
