helm:
  parameters:
  - name: image.repository
    value: ghcr.io/dungbik/flipnote-cardset
    forcestring: true
  - name: image.tag
    value: main@sha256:775499f9c6c1e28516d1f6507dcbe2d669085c717d80e68995c6a1d01e8ea28f
    forcestring: true
