helm:
  parameters:
  - name: image.repository
    value: ghcr.io/dungbik/flipnote-cardset
    forcestring: true
  - name: image.tag
    value: main@sha256:e6124504504b16433e99525b070976ec90299eed13dda9dc5bd0a17880e2374a
    forcestring: true
