helm:
  parameters:
  - name: image.repository
    value: ghcr.io/dungbik/flipnote-cardset
    forcestring: true
  - name: image.tag
    value: main@sha256:e0918c45d26a44366e760ae570c1815be484295b828c60e23dc6b63b7b4d281e
    forcestring: true
