apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flipnote-infra
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/FlipNoteTeam/FlipNote-Infra.git
    targetRevision: main
    path: argocd/infra
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
