helm:
  parameters:
  - name: image.repository
    value: dungbik/flipnote-image
    forcestring: true
  - name: image.tag
    value: main@sha256:aeb417f7e099081f5fefd791945169710469ade67582884602a6507047b777dc
    forcestring: true
