helm:
  parameters:
  - name: image.repository
    value: dungbik/flipnote-image
    forcestring: true
  - name: image.tag
    value: main@sha256:252a1657cd1a31cdd8329e4f6292f4e5210d366303bd8a6fbeb25cfe09464631
    forcestring: true
