helm:
  parameters:
  - name: image.repository
    value: dungbik/flipnote-image
    forcestring: true
  - name: image.tag
    value: main@sha256:fb30371a4c07fb04c4655d74ad0a14e500ed9dbce7e157a9c5004efc364ae941
    forcestring: true
